spring:
  profiles:
    active: dev
  mail:
    username: biharyoga123@gmail.com
    password: Password@123
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
          
forgot:
  password:
    email:
      send:
        from: biharyoga123@gmail.com
        

        

        
        
admin:
  create:
    account:
      email:
        send:
          from: biharyoga123@gmail.com
  authentication: false

  user:
     email: nikagrl19@gmail.com
        

server:
  port: 8080
---
#dev profile
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yoga?autoReconnect=true&useSSL=false
    username: root
    password: Password1
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 360000
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: false
      

      

