logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    com.bsy.live: DEBUG

server:
  port: 8081
  
spring:
  profiles:
    active: dev
    
vimeo:
  check:
    user:
      live:
        quota:
          url: https://api.vimeo.com/me
          
---

#dev profile

spring:
  profiles: dev


---

#integration profile


  



  
