logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    com.bsy.live: DEBUG

spring:
  profiles:
    active: dev
    
vimeo:
  check:
    user:
      live:
        quota:
          url: https://api.vimeo.com/me
          
---

#dev profile

spring:
  profiles: dev

server:
  port: 8081
  
 

---

#integration profile

spring:
  profiles: integration
  
server:
  port: 8082



  
